// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpuwnvdukidfapgrukhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwdXdudmR1a2lkZmFwZ3J1a2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTE0MzIsImV4cCI6MjA2NDU2NzQzMn0.8Hx8sSn4ZJ48lR2xsmcILfLUZI76s7k4FmM_w6h3ggg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);